name: Update dist
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: run build dist
        run: |
          ./nvmw npm set progress=false
          ./nvmw npm test
          ./nvmw npm run build

      - name: setup git config
        run: |
          # Setup git username and email
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Publish package
        id: publish-package
        run: |
          ./nvmw npm config set //npm.pkg.github.com/:_authToken ${TOKEN}
          ./nvmw npm unpublish --force mapbox-gl-draw@${GITHUB_REF##*/} || echo "Failed to unpublish package"
          ./nvmw npm version 1.3.1-$(date +"%Y%m%d%H%M%S") -commit-hooks false -git-tag-version false
          ./nvmw npm publish --tag ${GITHUB_REF##*/}
          ./nvmw npm run versions
          echo "VERSION=$(cat ./public/version-npm.txt)" >> $GITHUB_OUTPUT
        env:
          TOKEN: '${{secrets.GITHUB_TOKEN}}'

      - uses: fregante/setup-git-user@v1

      - name: Add tag
        if: github.ref == 'refs/heads/main'
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.publish-package.outputs.VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'