name: Build PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: run test and build dist
        run: |
          ./nvmw npm set progress=false
          ./nvmw npm test
          ./nvmw npm run build
