name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: bahmutov/npm-install@v1

      - name: Install deps and build
        run: |
          ./nvmw npm set progress=false
          ./nvmw npm test
          ./nvmw npm run prepublishOnly

      - uses: razor54/build-and-tag-action@v2.1.2
        with:
          additional_files: 'dist/mapbox-gl-draw.js,dist/mapbox-gl-draw.js.map,dist/mapbox-gl-draw-unminified.js,dist/mapbox-gl-draw-unminified.js.map,dist/mapbox-gl-draw.css,dist/svg/combine.svg,dist/svg/line.svg,dist/svg/point.svg,dist/svg/polygon.svg,dist/svg/trash.svg,dist/svg/uncombine.svg,types/index.d.ts'
          js_package: 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
